# Generated by Django 5.2.6 on 2025-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('car_selling_no', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('warranty', models.DateField()),
            ],
        ),
    ]
